### ISSUE TITLE
bug: broken link  

### ISSUE THREAD

**Issue by tusharnankani** [AmruthPillai/Grover-Timeline#1]
Hi

There's a broken link at the end hyperlinked for `Source Code` here

![image](https://user-images.githubusercontent.com/61280281/146868777-59bdcf4d-67a2-436f-98a6-cb33b3e81f9d.png)

https://github.com/AmruthPillai/GroverTimeline

![image](https://user-images.githubusercontent.com/61280281/146868822-d60dcc77-c13b-41d7-b472-c3f88ac4938e.png)

**Comment by amruthpillai** [comment]
Fixed now, thank you for your eagle eyes 🦅
